[package]
name = "arevel"
version = "0.1.0"
authors = ["Feni Varughese <feni727@gmail.com>"]
edition = "2018"

[dependencies]
# actix-web = "0.7"
# serde_derive = "1.0.93"
# serde = "1.0.93"

# Allow us to catch panics in parsing, eval etc. without bringing down the system.
[profile.debug]
panic = "unwind"

[profile.release]
panic = "unwind"




[buiild]
rustflags = "-C target-cpu=native"
