apiVersion: apps/v1
kind: Deployment
metadata:
  name: appy-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appy
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: appy
    spec:
      containers:
      - name: appy
        image: us.gcr.io/appassembly/appy:latest
        env:
          - name: ENVIRONMENT
            value: PROD
          - name: K8_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K8_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PGDATABASE
            value: aadb
          - name: PGUSER
            value: appy
          - name: PGHOST
            valueFrom:
              secretKeyRef:
                name: appy-secrets
                key: PGHOST
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: appy-secrets
                key: PGPASSWORD
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: appy-secrets
                key: SECRET_KEY
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: appy-service
  labels:
    name: appy
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: appy
  type: LoadBalancer
