apiVersion: apps/v1
kind: Deployment
metadata:
  name: aasm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aasm
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aasm
    spec:
      containers:
      - name: aasm
        image: us.gcr.io/appassembly/aasm:latest
        env:
          - name: ENVIRONMENT
            value: PROD
          - name: K8_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K8_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: aasm-secrets
                key: DATABASE_URL
        ports:
        - containerPort: 9080

---

apiVersion: v1
kind: Service
metadata:
  name: aasm-service
  labels:
    name: aasm
spec:
  ports:
  - port: 80
    targetPort: 9080
  selector:
    app: aasm
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: aa-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
    - host: appassembly.io
      http:
        paths:
        - backend:
            serviceName: appy-service
            servicePort: 80
    - http:
        paths:
        - backend:
            serviceName: aasm-service
            servicePort: 80

