apiVersion: apps/v1
kind: Deployment
metadata:
  name: aasm-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aasm
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aasm
    spec:
      containers:
      - name: aasm
        image: us.gcr.io/appassembly/aasm:latest
        env:
          - name: ENVIRONMENT
            value: PROD
          - name: K8_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K8_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: K8_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: aasm-secrets
                key: DATABASE_URL
        ports:
        - containerPort: 9080
        readinessProbe:
            httpGet:
              path: /_info/health
              port: 9080
        livenessProbe:
            httpGet:
              path: /_info/health
              port: 9080

---

apiVersion: v1
kind: Service
metadata:
  name: aasm-service
  labels:
    name: aasm
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    protocol: TCP
    name: aasm-port
  selector:
    app: aasm


---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: aa-ingress
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /
        kubernetes.io/ingress.global-static-ip-name: aa-public
spec:
    rules:
    - host: appassembly.io
      http:
        paths:
        - backend:
            serviceName: appy-service
            servicePort: 8000
    - http:
        paths:
        - backend:
            serviceName: aasm-service
            servicePort: 9080