apiVersion: v1
kind: ReplicationController
metadata:
  name: appy-rc
  labels:
    name: appy
spec:
  replicas: 2
  selector:
    name: appy
  template:
    metadata:
      labels:
        name: appy
    spec:
      containers:
        - name: appy
          image: us.gcr.io/arevel-209217/appy:latest
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DATABASE_NAME
              value: app_db
            - name: DATABASE_USER
              value: app_db_user
            - name: DATABASE_PASSWORD
              value: app_db_pw
          ports:
            - containerPort: 8000
